### ISSUE TITLE
Beskonačna petlja u IDAstar solveru

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp/2020_Lojdova-slagalica#1]
Kolega je pokrenuo projekat i dobio beskonačnu petlju (prekinuo nakon nekog vremena).
```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
Process ProcessSolver-2:
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "main.py", line 98, in run
    result = self._solver.solve(state)
  File "/home/cugur/Desktop/PP_Projects_2020/2020_Lojdova-slagalica/src/IDAstar.py", line 81, in solve
    self._solve_threshold(start_state, threshold)
  File "/home/cugur/Desktop/PP_Projects_2020/2020_Lojdova-slagalica/src/IDAstar.py", line 45, in _solve_threshold
    cost_guess = cur_dist + h(next_state)
  File "/home/cugur/Desktop/PP_Projects_2020/2020_Lojdova-slagalica/utils/utils.py", line 79, in h
    cost += abs(x % N - j) + abs(x // N - i)
KeyboardInterrupt
```

**Comment by 4eyes4u** [comment]
A* i IDA* za 4x4 slagalice prividno ne rade. Treba im previše vremena da je reše i stiče se utisak da je u pitanju beskonačna petlja.  WA* svaku slagalicu treba da reše u najviše nekoliko sekundi.

Ako je u pitanju 3x3 slagalica to ne sme da se dešava pa bih Vas zamolio da mi pošaljete konkretan primer na kom se to dešava.

**Comment by ivan-ristovic** [comment]
@MilanCugur 

Mislim da je u pitanju bila 4x4 slagalica ali ne secam se koliko je dugo trajalo izvršavanje pa najbolje da Milan pošalje konkretan test primer.

**Comment by cugurm** [comment]
Da, radilo se o 4x4 varijanti. 

Mozda ne bi bilo lose postaviti short info o tome za (nestrpljivog) korisnika. 
Progres bar verovatno nije moguc, mozda aproksimacija ocekivanog vremena izvrsavanja ili prosto poruku da ce trajati nesto duze.

**Comment by 4eyes4u** [comment]
> Čim jedan algoritam(od dva koja je korisnik odabrao) završi rešavanje, **pristupa se grafičkoj simulaciji** rešavanja slagalice...
